### ISSUE TITLE
Imports from antu cannot be resolved

### ISSUE THREAD

**Issue by chrikoehn** [AntNLP/gnn-dep-parsing#3]
As @TimeLessLing already [pointed out](https://github.com/AntNLP/gnn-dep-parsing/issues/2#issuecomment-626268440_): It's impossible to run the code because imports from antu are needed but are not available there:
- `OrthogonalInitializer` https://github.com/AntNLP/gnn-dep-parsing/blob/0c795d6d1f8f01561ab822909dbcc6ea0a6c69e1/gnn-dep-parser/src/models/graph_nn_decoder.py#L6
- `DeepBiRNNBuilder` (is it supposed to be `DeepBiLSTMBuilder`?) https://github.com/AntNLP/gnn-dep-parsing/blob/0c795d6d1f8f01561ab822909dbcc6ea0a6c69e1/gnn-dep-parser/src/train.py#L54

**Comment by JT-Ushio** [comment]
Sorry for the late reply,
I was unable to access the code of antu v0.0.5 for 4 months due to the COVID-19.
I've rewritten some code that the gnn parser relies on, and updated antu v0.0.5a.
I also tested well in a new environment, everything is working now~

**Comment by chrikoehn** [comment]
I'm sorry this happened to you. 
Thank you for addressing the issue. I will try the code later.
