### ISSUE TITLE
Compatible Eigen for dynet 2.0.0 are not available

### ISSUE THREAD

**Issue by Jivnesh** [AntNLP/gnn-dep-parsing#6]
I am facing a problem with the installation. For dynet2.0.0, the required Eigen version is not available. Is it possible for you to share the same? Or what is the alternative? Can I use this code with the latest version of dynet?

**Comment by JT-Ushio** [comment]
Dear @Jivnesh , thank you for your interest in our work! 

I also found that the version of Eigen needed for Dynet 2.0 was not available.
Here I provide a copy of the Eigen library required for Dynet 2.0.3, which has been tested to run our parser successfully.
[Eigen-2355b22(-r NUM).zip](https://drive.google.com/file/d/1PxHJdDaG6SvjV-6_6eKnYNApkMR0DaGz/view?usp=sharing)

I hope this helps!

**Comment by Jivnesh** [comment]
Thanks for the quick reply. I will try this. @JT-Ushio
